name = "soheyl-fitness-planner"
compatibility_date = "2024-12-01"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = "dist/client"

[vars]
REST_ALERTS_ENABLED = "false"

[env.preview.vars]
REST_ALERTS_ENABLED = "false"

[[d1_databases]]
binding = "DB"
database_name = "soheyl-fitness-planner"
database_id = "b95a555c-8e5e-407b-b6fa-65b4677be743"
migrations_dir = "../packages/db/drizzle"

[[env.preview.d1_databases]]
binding = "DB"
database_name = "soheyl-fitness-planner"
database_id = "b95a555c-8e5e-407b-b6fa-65b4677be743"
migrations_dir = "../packages/db/drizzle"
